- name: configure niginx
  hosts: 
  becamme: yes
  tasks:

    - name: disable default nginx
      ansible.builtin.command: dnf module disable nginx -y

    - name: enable 1.24 version nginx
      ansible.builtin.command: dnf module enable nginx:1.24 -y 

    - name: install nginx
      ansible.builtin.dnf:
        name: nginx
        state: present

    - name: start and enable the nginx service
      ansible.built.service:
        name: nginx
        state: started
        enabled: yes

    - name: remove default content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent

    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: download frontend content
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
        dest: /tmp/frontend-v3.zip

    - name: unzip frontend content
      ansible.builtin.archive:
        src: /tmp/frontend-v3.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: remove default nginx conf
      ansible.builtin.file:
        src: /etc/nginx/nginx.conf
        state: absent
    
    - name: add roboshop nginx conf
      ansible.builtin.file:
        src: nginx.conf
        dest: /etc/nginx/nginx.conf
        
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        

